'use client';
import { useEffect, useState } from 'react';
import { createBrowserClient } from '@/lib/supabase/client';
import { toast } from 'sonner';

export function AIChat(){
 const supabase=createBrowserClient(); const [chats,setChats]=useState<any[]>([]); const [chatId,setChatId]=useState<string|undefined>(); const [messages,setMessages]=useState<any[]>([]); const [text,setText]=useState(''); const [allowContext,setAllowContext]=useState(true); const [loading,setLoading]=useState(false);
 async function loadChats(){const {data}=await supabase.from('ai_chats').select('*').order('updated_at',{ascending:false}); setChats(data||[]); if(!chatId && data?.[0]) setChatId(data[0].id)}
 async function loadMessages(){ if(!chatId) return; const {data}=await supabase.from('ai_messages').select('*').eq('chat_id',chatId).order('created_at'); setMessages(data||[])}
 useEffect(()=>{loadChats()},[]); useEffect(()=>{loadMessages()},[chatId]);
 async function send(e:React.FormEvent){ e.preventDefault(); setLoading(true); try{ const res=await fetch('/api/ai/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chatId,message:text,allowContext})}); const json=await res.json(); if(!res.ok) throw new Error(json.message||json.error||'Gagal chat'); setText(''); setChatId(json.chatId); await loadChats(); await loadMessages(); }catch(err:any){toast.error(err.message)} finally{setLoading(false)} }
 async function clear(){ if(!chatId) return; await supabase.from('ai_messages').delete().eq('chat_id',chatId); loadMessages(); }
 return <div className="grid gap-5 lg:grid-cols-[280px_1fr]"><aside className="neo-card"><button className="neo-btn w-full" onClick={()=>{setChatId(undefined);setMessages([])}}>Chat Baru</button><div className="mt-4 space-y-2">{chats.map(c=><button key={c.id} onClick={()=>setChatId(c.id)} className="w-full rounded-2xl bg-white/5 p-3 text-left text-sm font-bold">{c.title}</button>)}</div></aside><section className="neo-card min-h-[70vh]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-neoLime">AgronityAI</p><h1 className="page-title mt-2">Chat AI</h1><label className="mt-4 flex items-center gap-2 text-sm text-white/60"><input type="checkbox" checked={allowContext} onChange={e=>setAllowContext(e.target.checked)}/> Izinkan AI membaca konteks jadwal, nilai, jurnal, dan keuangan saya</label></div><div className="mt-5 max-h-[55vh] space-y-3 overflow-auto rounded-3xl border border-white/10 bg-black/20 p-3">{messages.map(m=><div key={m.id} className={m.role==='user'?'ml-auto max-w-[85%] rounded-3xl bg-neoLime p-4 text-black':'mr-auto max-w-[85%] rounded-3xl bg-white/10 p-4 text-white'}><p className="whitespace-pre-wrap text-sm">{m.content}</p></div>)}</div><form onSubmit={send} className="mt-3 flex gap-2"><input className="neo-input" value={text} onChange={e=>setText(e.target.value)} placeholder="Tanya jadwal, IPK, tugas, caption, refleksi..."/><button disabled={loading} className="neo-btn">{loading?'...':'Kirim'}</button></form><button onClick={clear} className="neo-btn-muted mt-3">Hapus Riwayat Chat Ini</button></section></div>
}
