'use client';
import { useEffect, useState } from 'react';
import { createBrowserClient } from '@/lib/supabase/client';
import { toast } from 'sonner';

export function ChatApp(){
 const supabase=createBrowserClient(); const [me,setMe]=useState<string>(''); const [profiles,setProfiles]=useState<any[]>([]); const [rooms,setRooms]=useState<any[]>([]); const [room,setRoom]=useState<any>(); const [messages,setMessages]=useState<any[]>([]); const [body,setBody]=useState(''); const [streak,setStreak]=useState<any>();
 async function boot(){ const {data:{user}}=await supabase.auth.getUser(); if(!user) return; setMe(user.id); const {data:p}=await supabase.from('profiles').select('id,full_name,avatar_url').neq('id',user.id).limit(100); setProfiles(p||[]); const {data:r}=await supabase.from('chat_rooms').select('*, chat_participants(*)').order('updated_at',{ascending:false}); setRooms(r||[]); }
 async function loadMessages(roomId:string){ const {data}=await supabase.from('chat_messages').select('*, profiles:sender_id(full_name,avatar_url)').eq('room_id',roomId).order('created_at'); setMessages(data||[]); const {data:s}=await supabase.from('chat_streaks').select('*').eq('room_id',roomId).maybeSingle(); setStreak(s); }
 useEffect(()=>{boot()},[]); useEffect(()=>{ if(!room) return; loadMessages(room.id); const ch=supabase.channel(`chat-${room.id}`).on('postgres_changes',{event:'*',schema:'public',table:'chat_messages',filter:`room_id=eq.${room.id}`},()=>loadMessages(room.id)).on('postgres_changes',{event:'*',schema:'public',table:'chat_streaks',filter:`room_id=eq.${room.id}`},()=>loadMessages(room.id)).subscribe(); return()=>{supabase.removeChannel(ch)} },[room]);
 async function startDirect(otherId:string){ try{ const {data:{user}}=await supabase.auth.getUser(); if(!user) throw new Error('Login dulu'); const {data:r,error}=await supabase.from('chat_rooms').insert({type:'direct',created_by:user.id}).select('*').single(); if(error) throw error; const {error:e2}=await supabase.from('chat_participants').insert([{room_id:r.id,user_id:user.id},{room_id:r.id,user_id:otherId}]); if(e2) throw e2; setRoom(r); boot(); }catch(e:any){toast.error(e.message)} }
 async function send(e:React.FormEvent){ e.preventDefault(); if(!room || !body.trim()) return; const {error}=await supabase.from('chat_messages').insert({room_id:room.id,sender_id:me,body}); if(error) toast.error(error.message); else setBody(''); }
 return <div className="grid gap-5 lg:grid-cols-[320px_1fr]"><aside className="neo-card"><p className="text-xs font-black uppercase tracking-[.2em] text-neoLime">Chat Streak</p><h1 className="mt-2 text-3xl font-black">Chat</h1><h2 className="mt-5 font-black">Room</h2><div className="mt-2 space-y-2">{rooms.map(r=><button key={r.id} onClick={()=>setRoom(r)} className="w-full rounded-2xl bg-white/5 p-3 text-left text-sm">Room {r.id.slice(0,8)}</button>)}</div><h2 className="mt-5 font-black">Mulai Chat</h2><div className="mt-2 max-h-72 space-y-2 overflow-auto">{profiles.map(p=><button key={p.id} onClick={()=>startDirect(p.id)} className="w-full rounded-2xl bg-white/5 p-3 text-left text-sm">{p.full_name||p.id}</button>)}</div></aside><section className="neo-card min-h-[75vh]"><div className="flex items-center justify-between"><div><h1 className="page-title">Chat Angkatan</h1><p className="mt-2 text-sm text-white/60">Streak bertambah jika dua pengguna saling chat dalam 24 jam.</p></div>{streak&&<div className="rounded-3xl bg-orange-400/10 p-4 text-center"><p className="text-3xl font-black text-orange-300">🔥 {streak.current_count}</p><p className="text-xs text-white/50">{streak.status}</p></div>}</div><div className="mt-5 max-h-[55vh] space-y-2 overflow-auto rounded-3xl border border-white/10 bg-black/20 p-3">{messages.map(m=><div key={m.id} className={m.sender_id===me?'ml-auto max-w-[80%] rounded-3xl bg-neoLime p-3 text-black':'mr-auto max-w-[80%] rounded-3xl bg-white/10 p-3'}><p className="text-xs opacity-60">{m.profiles?.full_name}</p><p>{m.body}</p></div>)}</div><form onSubmit={send} className="mt-3 flex gap-2"><input className="neo-input" value={body} onChange={e=>setBody(e.target.value)} placeholder={room?'Ketik pesan...':'Pilih/mulai room dulu'} disabled={!room}/><button className="neo-btn" disabled={!room}>Kirim</button></form></section></div>
}
