'use client';
import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@/lib/supabase/client';
import { uploadToBucket } from '@/lib/upload';
import { STORAGE_BUCKETS } from '@/lib/app';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie } from 'recharts';
import { toast } from 'sonner';

const cats=['makan','transport','kos','kuliah','print','organisasi','hiburan','kesehatan','tabungan','lainnya'];
export function FinanceApp(){
 const supabase=createBrowserClient(); const [items,setItems]=useState<any[]>([]); const [type,setType]=useState('expense'); const [amount,setAmount]=useState(''); const [category,setCategory]=useState('makan'); const [wallet,setWallet]=useState('cash'); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [note,setNote]=useState(''); const [file,setFile]=useState<File|null>(null); const [budget,setBudget]=useState(1000000);
 async function load(){const {data}=await supabase.from('finance_transactions').select('*').order('transaction_date',{ascending:false}).limit(200); setItems(data||[])} useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){ e.preventDefault(); try{ const {data:{user}}=await supabase.auth.getUser(); if(!user) throw new Error('Login dulu'); let up:any={}; if(file) up=await uploadToBucket(STORAGE_BUCKETS.finance,file,'receipts',['image/','application/pdf'],15); const {error}=await supabase.from('finance_transactions').insert({user_id:user.id,type,amount:Number(amount),category,wallet,transaction_date:date,note,receipt_url:up.publicUrl,receipt_path:up.path}); if(error) throw error; await supabase.rpc('record_activity',{p_activity_type:'finance_record',p_metadata:{type,amount:Number(amount)}}); toast.success('Transaksi tersimpan'); setAmount(''); setNote(''); setFile(null); load(); }catch(e:any){toast.error(e.message)} }
 const expense=items.filter(i=>i.type==='expense').reduce((a,i)=>a+Number(i.amount),0), income=items.filter(i=>i.type==='income').reduce((a,i)=>a+Number(i.amount),0); const byCat=useMemo(()=>Object.values(items.filter(i=>i.type==='expense').reduce((a:any,i:any)=>{a[i.category] ||= {category:i.category,total:0}; a[i.category].total+=Number(i.amount); return a},{})),[items]); const byDay=useMemo(()=>Object.values(items.reduce((a:any,i:any)=>{a[i.transaction_date] ||= {date:i.transaction_date,expense:0,income:0}; a[i.transaction_date][i.type]+=Number(i.amount); return a},{})),[items]);
 return <div className="space-y-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-neoLime">Finance App</p><h1 className="page-title mt-2">Pencatat Keuangan</h1><p className="mt-3 text-white/60">Pemasukan, pengeluaran, budget, target tabungan, bukti struk, grafik, dan insight AI.</p></div><section className="grid gap-4 md:grid-cols-3"><Stat label="Pemasukan" value={income}/><Stat label="Pengeluaran" value={expense}/><Stat label="Sisa Budget" value={budget-expense}/></section><form onSubmit={save} className="neo-card grid gap-3 md:grid-cols-3"><select className="neo-input" value={type} onChange={e=>setType(e.target.value)}><option value="expense">Pengeluaran</option><option value="income">Pemasukan</option></select><input className="neo-input" type="number" placeholder="Nominal" value={amount} onChange={e=>setAmount(e.target.value)} required/><select className="neo-input" value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select><input className="neo-input" value={wallet} onChange={e=>setWallet(e.target.value)} placeholder="cash/e-wallet/bank"/><input className="neo-input" type="date" value={date} onChange={e=>setDate(e.target.value)}/><input className="neo-input" type="file" accept="image/*,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><textarea className="neo-input md:col-span-2" placeholder="Catatan" value={note} onChange={e=>setNote(e.target.value)}/><button className="neo-btn">Simpan</button></form><section className="grid gap-4 xl:grid-cols-2"><div className="neo-card h-80"><h2 className="font-black">Harian</h2><ResponsiveContainer width="100%" height="85%"><BarChart data={byDay as any[]}><XAxis dataKey="date"/><YAxis/><Tooltip/><Bar dataKey="expense"/><Bar dataKey="income"/></BarChart></ResponsiveContainer></div><div className="neo-card h-80"><h2 className="font-black">Kategori Terbesar</h2><ResponsiveContainer width="100%" height="85%"><PieChart><Pie data={byCat as any[]} dataKey="total" nameKey="category" label/></PieChart></ResponsiveContainer></div></section><section className="neo-card"><h2 className="font-black">Riwayat</h2><div className="mt-3 space-y-2">{items.map(i=><div key={i.id} className="flex justify-between rounded-2xl bg-white/5 p-3"><span>{i.category} • {i.note}</span><b>{i.type==='expense'?'-':'+'}Rp{Number(i.amount).toLocaleString('id-ID')}</b></div>)}</div></section></div>
}
function Stat({label,value}:{label:string;value:number}){return <div className="neo-card"><p className="text-sm text-white/50">{label}</p><p className="mt-2 text-3xl font-black">Rp{Number(value).toLocaleString('id-ID')}</p></div>}
