'use client';
import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@/lib/supabase/client';
import { uploadToBucket } from '@/lib/upload';
import { STORAGE_BUCKETS } from '@/lib/app';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { toast } from 'sonner';

const tags=['kuliah','organisasi','tugas','praktikum','personal','keuangan','kesehatan'];
export function JournalApp(){
 const supabase=createBrowserClient(); const [items,setItems]=useState<any[]>([]); const [entryDate,setEntryDate]=useState(new Date().toISOString().slice(0,10)); const [mood,setMood]=useState('😊'); const [title,setTitle]=useState(''); const [body,setBody]=useState(''); const [pickedTags,setPickedTags]=useState<string[]>([]); const [file,setFile]=useState<File|null>(null); const [q,setQ]=useState('');
 async function load(){const {data}=await supabase.from('journals').select('*, journal_attachments(*)').order('entry_date',{ascending:false}); setItems(data||[])} useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){ e.preventDefault(); try{ const {data:{user}}=await supabase.auth.getUser(); if(!user) throw new Error('Login dulu'); const {data:j,error}=await supabase.from('journals').insert({user_id:user.id,entry_date:entryDate,mood,title,body,tags:pickedTags,is_private:true}).select('id').single(); if(error) throw error; if(file){ const up=await uploadToBucket(STORAGE_BUCKETS.journal,file,'journal',['image/'],10); await supabase.from('journal_attachments').insert({journal_id:j.id,user_id:user.id,file_url:up.publicUrl,file_path:up.path,file_type:file.type}); } await supabase.rpc('record_activity',{p_activity_type:'journal_write',p_metadata:{mood}}); toast.success('Jurnal tersimpan'); setTitle(''); setBody(''); setFile(null); load(); }catch(e:any){toast.error(e.message)} }
 async function remove(id:string){ if(!confirm('Hapus jurnal?')) return; await supabase.from('journals').delete().eq('id',id); load(); }
 const filtered=items.filter(i=>(i.title+i.body+(i.tags||[]).join(' ')).toLowerCase().includes(q.toLowerCase()));
 const moodStats=useMemo(()=>Object.entries(items.reduce((a:any,i:any)=>{a[i.mood]=(a[i.mood]||0)+1;return a},{})).map(([mood,count])=>({mood,count})),[items]);
 return <div className="space-y-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-neoLime">Private by default</p><h1 className="page-title mt-2">Journalling</h1><p className="mt-3 text-white/60">Jurnal harian, mood tracker, tag, lampiran foto, search, statistik, dan siap direfleksikan AgronityAI jika kamu izinkan.</p></div><form onSubmit={save} className="neo-card space-y-3"><div className="grid gap-2 md:grid-cols-3"><input className="neo-input" type="date" value={entryDate} onChange={e=>setEntryDate(e.target.value)}/><select className="neo-input" value={mood} onChange={e=>setMood(e.target.value)}>{['😊','😐','😔','🔥','😴','🤯'].map(m=><option key={m}>{m}</option>)}</select><input className="neo-input" type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></div><input className="neo-input" placeholder="Judul jurnal" value={title} onChange={e=>setTitle(e.target.value)} required/><textarea className="neo-input min-h-36" placeholder="Tulis jurnalmu..." value={body} onChange={e=>setBody(e.target.value)} required/><div className="flex flex-wrap gap-2">{tags.map(t=><button type="button" onClick={()=>setPickedTags(pickedTags.includes(t)?pickedTags.filter(x=>x!==t):[...pickedTags,t])} className={pickedTags.includes(t)?'neo-btn':'neo-btn-muted'} key={t}>{t}</button>)}</div><button className="neo-btn">Simpan Jurnal</button></form><section className="grid gap-4 lg:grid-cols-[1fr_320px]"><div className="neo-card"><input className="neo-input mb-4" placeholder="Search jurnal..." value={q} onChange={e=>setQ(e.target.value)}/><div className="space-y-3">{filtered.map(i=><article key={i.id} className="rounded-3xl border border-white/10 bg-white/5 p-4"><div className="flex justify-between"><div><p className="text-xs text-neoLime font-black">{i.entry_date} • {i.mood}</p><h3 className="text-xl font-black">{i.title}</h3></div><button className="text-red-300" onClick={()=>remove(i.id)}>Hapus</button></div><p className="mt-2 whitespace-pre-wrap text-sm text-white/70">{i.body}</p><p className="mt-2 text-xs text-white/40">{(i.tags||[]).join(', ')}</p></article>)}</div></div><div className="neo-card h-80"><h2 className="font-black">Statistik Mood</h2><ResponsiveContainer width="100%" height="85%"><BarChart data={moodStats}><XAxis dataKey="mood"/><YAxis/><Tooltip/><Bar dataKey="count"/></BarChart></ResponsiveContainer></div></section></div>
}
