'use client';
import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@/lib/supabase/client';
import { uploadToBucket } from '@/lib/upload';
import { STORAGE_BUCKETS } from '@/lib/app';
import { CameraCapture } from '@/components/camera-capture';
import { parseKhsText, cumulativeStats, neededAverage } from '@/lib/ipk';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, BarChart, Bar, PieChart, Pie, Cell } from 'recharts';
import { createWorker } from 'tesseract.js';
import { toast } from 'sonner';

export function KhsManager(){
 const supabase=createBrowserClient(); const [file,setFile]=useState<File|null>(null); const [raw,setRaw]=useState(''); const [semester,setSemester]=useState(1); const [rows,setRows]=useState<any[]>([]); const [saved,setSaved]=useState<any[]>([]); const [target,setTarget]=useState(3.5); const [nextSks,setNextSks]=useState(20); const [ocring,setOcring]=useState(false);
 async function load(){const {data}=await supabase.from('khs_courses').select('*').order('semester'); setSaved(data||[])} useEffect(()=>{load()},[]);
 async function runOcr(){ if(!file) return toast.error('Pilih file/foto dulu'); setOcring(true); try{ const worker=await createWorker('ind+eng'); const {data}=await worker.recognize(file); await worker.terminate(); setRaw(data.text); const parsed=parseKhsText(data.text); setSemester(parsed.semester); setRows(parsed.courses); toast.success(parsed.confidenceNote); }catch(e:any){toast.error(e.message)} finally{setOcring(false)} }
 function addRow(){ setRows([...rows,{course_name:'',sks:2,grade_letter:'A',grade_point:4,semester}]) }
 async function save(){ try{ const {data:{user}}=await supabase.auth.getUser(); if(!user) throw new Error('Login dulu'); let uploaded:any={}; if(file) uploaded=await uploadToBucket(STORAGE_BUCKETS.khs,file,'khs',['image/','application/pdf'],20); const {data:scan,error:scanErr}=await supabase.from('khs_scans').insert({user_id:user.id,semester,file_url:uploaded.publicUrl,file_path:uploaded.path,ocr_text:raw,status:'corrected'}).select('id').single(); if(scanErr) throw scanErr; const payload=rows.map(r=>({...r,user_id:user.id,scan_id:scan.id,semester:Number(semester),sks:Number(r.sks),grade_point:Number(r.grade_point)})); const {error}=await supabase.from('khs_courses').insert(payload); if(error) throw error; await supabase.rpc('record_activity',{p_activity_type:'khs_scan',p_metadata:{semester,count:payload.length}}); toast.success('KHS dan nilai tersimpan'); setRows([]); setFile(null); load(); }catch(e:any){toast.error(e.message)} }
 const graph=useMemo(()=>cumulativeStats(saved),[saved]); const need=useMemo(()=>neededAverage(saved,target,nextSks),[saved,target,nextSks]); const dist=Object.entries(saved.reduce((a:any,c:any)=>{a[c.grade_letter]=(a[c.grade_letter]||0)+1;return a},{})).map(([name,value])=>({name,value}));
 return <div className="space-y-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-neoLime">Scan KHS + Simulator IPK</p><h1 className="page-title mt-2">Pencatat Nilai</h1><p className="mt-3 text-white/60">OCR Tesseract.js membaca KHS, kamu koreksi, lalu simpan ke Supabase dan grafik IPK otomatis terhubung.</p></div><section className="neo-card space-y-3"><div className="flex flex-wrap gap-2"><input type="file" accept="image/*,application/pdf" className="neo-input max-w-md" onChange={e=>setFile(e.target.files?.[0]||null)}/><CameraCapture onCapture={setFile}/><button className="neo-btn" onClick={runOcr}>{ocring?'Scanning...':'Scan OCR'}</button></div><textarea className="neo-input min-h-32" value={raw} onChange={e=>setRaw(e.target.value)} placeholder="Teks OCR tampil di sini. Bisa paste manual juga."/><div className="flex gap-2"><button className="neo-btn-muted" onClick={()=>{const p=parseKhsText(raw); setSemester(p.semester); setRows(p.courses)}}>Parse Teks</button><button className="neo-btn-muted" onClick={addRow}>Tambah Baris</button><button className="neo-btn" onClick={save}>Simpan Nilai</button></div></section><section className="neo-card"><h2 className="text-xl font-black">Koreksi Hasil OCR</h2><div className="mt-4 overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left text-white/50"><th>Matkul</th><th>SKS</th><th>Nilai</th><th>Angka</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><input className="neo-input" value={r.course_name} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,course_name:e.target.value}:x))}/></td><td><input className="neo-input" type="number" value={r.sks} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,sks:e.target.value}:x))}/></td><td><input className="neo-input" value={r.grade_letter} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,grade_letter:e.target.value}:x))}/></td><td><input className="neo-input" type="number" step="0.01" value={r.grade_point} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,grade_point:e.target.value}:x))}/></td></tr>)}</tbody></table></div></section><section className="grid gap-4 xl:grid-cols-2"><Chart title="IPK Kumulatif" data={graph} dataKey="ipk"/><Chart title="IPS Semester" data={graph} dataKey="ips"/><Chart title="SKS per Semester" data={graph} dataKey="sks" bar/><div className="neo-card"><h2 className="font-black">Target IPK</h2><div className="mt-3 grid grid-cols-2 gap-2"><input className="neo-input" type="number" step="0.01" value={target} onChange={e=>setTarget(Number(e.target.value))}/><input className="neo-input" type="number" value={nextSks} onChange={e=>setNextSks(Number(e.target.value))}/></div><p className="mt-4 text-4xl font-black text-neoLime">{need}</p><p className="text-sm text-white/60">Rata-rata nilai angka semester berikutnya yang dibutuhkan.</p></div></section></div>
}
function Chart({title,data,dataKey,bar}:{title:string;data:any[];dataKey:string;bar?:boolean}){return <div className="neo-card h-80"><h2 className="font-black">{title}</h2><ResponsiveContainer width="100%" height="85%">{bar?<BarChart data={data}><XAxis dataKey="semester"/><YAxis/><Tooltip/><Bar dataKey={dataKey}/></BarChart>:<LineChart data={data}><XAxis dataKey="semester"/><YAxis/><Tooltip/><Line type="monotone" dataKey={dataKey}/></LineChart>}</ResponsiveContainer></div>}
