'use client';
import { useEffect, useState } from 'react';
import { createBrowserClient } from '@/lib/supabase/client';
import { uploadToBucket } from '@/lib/upload';
import { STORAGE_BUCKETS } from '@/lib/app';
import { CameraCapture } from '@/components/camera-capture';
import { Heart, MessageCircle, Bookmark, Flag, Trash2 } from 'lucide-react';
import { toast } from 'sonner';

export function SocialFeed() {
  const supabase = createBrowserClient();
  const [posts,setPosts]=useState<any[]>([]); const [caption,setCaption]=useState(''); const [file,setFile]=useState<File|null>(null); const [tab,setTab]=useState('terbaru');
  async function load(){ const q=supabase.from('social_posts_with_counts').select('*').order(tab==='populer'?'like_count':'created_at',{ascending:false}).limit(50); const {data,error}=await q; if(error) toast.error(error.message); else setPosts(data||[]); }
  useEffect(()=>{ load(); const ch=supabase.channel('social-feed').on('postgres_changes',{event:'*',schema:'public',table:'social_posts'},load).on('postgres_changes',{event:'*',schema:'public',table:'social_comments'},load).on('postgres_changes',{event:'*',schema:'public',table:'social_likes'},load).subscribe(); return()=>{supabase.removeChannel(ch)}; },[tab]);
  async function createPost(e:React.FormEvent){ e.preventDefault(); try{ let media:any={}; if(file){ media=await uploadToBucket(STORAGE_BUCKETS.social,file,'posts',['image/','video/'],50); }
    const {data:{user}}=await supabase.auth.getUser(); if(!user) throw new Error('Login dulu.');
    const {error}=await supabase.from('social_posts').insert({user_id:user.id,caption,media_url:media.publicUrl,media_path:media.path,media_type:file?.type.startsWith('video')?'video':'image'}); if(error) throw error;
    await supabase.rpc('record_activity',{p_activity_type:'social_post',p_metadata:{has_media:!!file}}); setCaption(''); setFile(null); toast.success('Postingan terkirim'); load();
  }catch(err:any){toast.error(err.message)} }
  async function like(id:string){ const {error}=await supabase.rpc('toggle_social_like',{p_post_id:id}); if(error) toast.error(error.message); }
  async function save(id:string){ const {error}=await supabase.rpc('toggle_social_save',{p_post_id:id}); if(error) toast.error(error.message); else toast.success('Status simpan diubah'); }
  async function report(id:string){ const reason=prompt('Alasan report?'); if(!reason) return; const {error}=await supabase.from('social_reports').insert({post_id:id,reason}); if(error) toast.error(error.message); else toast.success('Report dikirim ke admin'); }
  async function remove(id:string){ if(!confirm('Hapus postingan?')) return; const {error}=await supabase.from('social_posts').delete().eq('id',id); if(error) toast.error(error.message); else load(); }
  return <div className="space-y-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-neoLime">Realtime Social</p><h1 className="page-title mt-2">Agronity Social</h1><p className="mt-3 text-white/60">Feed internal angkatan: teks, foto/video, kamera native, like, komentar, simpan, report, dan realtime.</p></div>
    <form onSubmit={createPost} className="neo-card space-y-3"><textarea className="neo-input min-h-28" placeholder="Apa kabar Agronity hari ini?" value={caption} onChange={e=>setCaption(e.target.value)} required/><div className="flex flex-wrap gap-2"><input className="neo-input max-w-xs" type="file" accept="image/*,video/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><CameraCapture onCapture={setFile}/><button className="neo-btn" type="submit">Upload</button></div>{file&&<p className="text-xs text-white/50">File: {file.name}</p>}</form>
    <div className="flex gap-2 overflow-x-auto">{['terbaru','populer','teman angkatan'].map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'neo-btn':'neo-btn-muted'}>{t}</button>)}</div>
    <div className="grid gap-4 lg:grid-cols-2">{posts.map(p=><article key={p.id} className="neo-card"><div className="flex justify-between"><div><p className="font-black">{p.full_name || 'Mahasiswa Agronity'}</p><p className="text-xs text-white/40">{new Date(p.created_at).toLocaleString('id-ID')}</p></div><button onClick={()=>remove(p.id)} className="text-white/40 hover:text-red-300"><Trash2 size={16}/></button></div><p className="mt-4 whitespace-pre-wrap text-white/80">{p.caption}</p>{p.media_url && (p.media_type==='video'?<video controls src={p.media_url} className="mt-4 max-h-[520px] w-full rounded-3xl object-cover"/>:<img src={p.media_url} className="mt-4 max-h-[520px] w-full rounded-3xl object-cover" alt="post"/>)}<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>like(p.id)} className="neo-btn-muted"><Heart size={16}/>{p.like_count||0}</button><CommentButton post={p}/><button onClick={()=>save(p.id)} className="neo-btn-muted"><Bookmark size={16}/>Simpan</button><button onClick={()=>report(p.id)} className="neo-btn-muted"><Flag size={16}/>Report</button></div></article>)}</div></div>;
}
function CommentButton({post}:{post:any}){ const [open,setOpen]=useState(false); return <><button onClick={()=>setOpen(!open)} className="neo-btn-muted"><MessageCircle size={16}/>{post.comment_count||0}</button>{open&&<Comments postId={post.id}/>}</> }
function Comments({postId}:{postId:string}){ const supabase=createBrowserClient(); const [text,setText]=useState(''); const [items,setItems]=useState<any[]>([]); async function load(){const {data}=await supabase.from('social_comments_with_profiles').select('*').eq('post_id',postId).order('created_at'); setItems(data||[])} useEffect(()=>{load()},[]); async function send(){const {data:{user}}=await supabase.auth.getUser(); if(!user) return toast.error('Login dulu'); const {error}=await supabase.from('social_comments').insert({post_id:postId,user_id:user.id,body:text}); if(error) toast.error(error.message); else {setText(''); load();}} return <div className="fixed inset-0 z-[70] bg-black/80 p-4"><div className="mx-auto max-w-lg neo-card"><button className="neo-btn-muted mb-3" onClick={()=>history.back()}>Tutup manual: klik back/refresh</button><div className="max-h-[55vh] overflow-auto space-y-2">{items.map(c=><div key={c.id} className="rounded-2xl bg-white/5 p-3"><b>{c.full_name||'User'}</b><p className="text-sm text-white/70">{c.body}</p></div>)}</div><div className="mt-3 flex gap-2"><input className="neo-input" value={text} onChange={e=>setText(e.target.value)} placeholder="Komentar..."/><button className="neo-btn" onClick={send}>Kirim</button></div></div></div> }
